plugins:
  - jest
env:
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb-base
  - plugin:jest/recommended
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules: {
  "no-unused-vars": 0,
  "no-console": 0,
  "no-restricted-syntax": 0,
  "no-async-promise-executor": 0,
  "no-await-in-loop": 0
}
